DROP TABLE IF EXISTS `project_progress`;
CREATE TABLE `project_progress` (
  `id` varchar(20) DEFAULT NULL,
  `projectId` varchar(20) DEFAULT NULL,
  `pc1` varchar(21) DEFAULT NULL ,
  `pc2` varchar(21) DEFAULT NULL ,
  `pc3` varchar(21) DEFAULT NULL ,
  `pc4` varchar(21) DEFAULT NULL ,
  `pc5` varchar(21) DEFAULT NULL ,
  `pc6` varchar(21) DEFAULT NULL ,
  `pc7` varchar(21) DEFAULT NULL ,
  `pc8` varchar(21) DEFAULT NULL ,
  `pc9` varchar(21) DEFAULT NULL ,
  `pc10` varchar(21) DEFAULT NULL ,
  `pc11` varchar(21) DEFAULT NULL ,
  `pc12` varchar(21) DEFAULT NULL ,
  `pc13` varchar(21) DEFAULT NULL ,
  `pc14` varchar(21) DEFAULT NULL ,
  `pc15` varchar(21) DEFAULT NULL ,
  `pc16` varchar(21) DEFAULT NULL ,
  `pc17` varchar(21) DEFAULT NULL ,
  `pc18` varchar(21) DEFAULT NULL ,
  `pc19` varchar(21) DEFAULT NULL ,
  `pc20` varchar(21) DEFAULT NULL ,
  `pc21` varchar(21) DEFAULT NULL ,
  `pc22` varchar(21) DEFAULT NULL ,
  `pc23` varchar(21) DEFAULT NULL ,
  `pc24` varchar(21) DEFAULT NULL ,
  `pc25` varchar(21) DEFAULT NULL ,
  `pc26` varchar(21) DEFAULT NULL ,
  `pc27` varchar(21) DEFAULT NULL ,
  `pc28` varchar(21) DEFAULT NULL ,
  `pc29` varchar(21) DEFAULT NULL ,
  `pc30` varchar(21) DEFAULT NULL ,
  `pc31` varchar(21) DEFAULT NULL ,
  `pc32` varchar(21) DEFAULT NULL ,
  `mc1` text DEFAULT NULL ,
  `mc2` text DEFAULT NULL ,
  `mc3` text DEFAULT NULL ,
  `mc4` text DEFAULT NULL ,
  `mc5` text DEFAULT NULL ,
  `mc6` text DEFAULT NULL ,
  `mc7` text DEFAULT NULL ,
  `mc8` text DEFAULT NULL ,
  `mc9` text DEFAULT NULL ,
  `mc10` text DEFAULT NULL ,
  `mc11` text DEFAULT NULL ,
  `mc12` text DEFAULT NULL ,
  `mc13` text DEFAULT NULL ,
  `mc14` text DEFAULT NULL ,
  `mc15` text DEFAULT NULL ,
  `mc16` text DEFAULT NULL ,
  `mc17` text DEFAULT NULL ,
  `mc18` text DEFAULT NULL ,
  `mc19` text DEFAULT NULL ,
  `mc20` text DEFAULT NULL ,
  `mc21` text DEFAULT NULL ,
  `mc22` text DEFAULT NULL ,
  `mc23` text DEFAULT NULL ,
  `mc24` text DEFAULT NULL ,
  `mc25` text DEFAULT NULL ,
  `mc26` text DEFAULT NULL ,
  `mc27` text DEFAULT NULL ,
  `mc28` text DEFAULT NULL ,
  `mc29` text DEFAULT NULL ,
  `mc30` text DEFAULT NULL ,
  `mc31` text DEFAULT NULL ,
  `mc32` text DEFAULT NULL ,
  `isDeleted` varchar(5) DEFAULT NULL,
  `createTime` datetime DEFAULT NULL,
  `updateTime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `mainmaterial` ADD `isChecked` VARCHAR(5) CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `productDeliver`;

update `system` set `paramValue`='version-7.8' where `id`='4';